### ISSUE TITLE
怎么用？？

### ISSUE THREAD

**Issue by limengmingx** [Sdu0/py-mysql-elasticsearch#1]
所以说这个轮子怎么用呀(O_o)(o_O)

**Comment by ddusen** [comment]
我想你应该先把项目clone到自己的电脑上，
然后修改core/config.py配置文件（mysql配置、mysqlbinlog配置、es配置），
之后按照requirments文件里面的要求安装依赖环境，
最后按照你的需求，修改部分文件代码（README.md里面有一些说明，可以看下），经过一些调试应该就可以正常运行了。🙂
